services:
  - type: web
    name: quits-api
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: node src/index.js
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: PORT
        value: 10000
      - key: NODE_VERSION
        value: "22.x"
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_CALLBACK_URL
        sync: false
      - key: CLIENT_URL
        value: https://www.quits.cc
      - key: SESSION_SECRET
        sync: false
      - key: NODE_ENV
        value: production
      - key: API_URL
        value: https://api.quits.cc
    buildFilter:
      paths:
        - server/**
        - server/package.json
        - server/package-lock.json
        - server/.env
    healthCheckPath: /api/test-cors
    autoDeploy: true
    github:
      repo: matsottens/quits-backend
      branch: main
    headers:
      - path: /*
        name: Strict-Transport-Security
        value: max-age=31536000; includeSubDomains
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Vary
        value: Origin 