services:
  - type: web
    name: quits-api
    env: node
    buildCommand: npm install
    startCommand: node server/src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_CALLBACK_URL
        value: https://api.quits.cc/auth/google/callback
      - key: SESSION_SECRET
        generateValue: true
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: CLIENT_URL
        value: https://quits.cc
      - key: API_URL
        value: https://api.quits.cc
    healthCheckPath: /api/test-cors
    autoDeploy: true
    github:
      repo: matsottens/quits-backend
      branch: main
    buildFilter:
      paths:
        - src/**
        - package.json
        - package-lock.json
    headers:
      - path: /*
        name: Strict-Transport-Security
        value: max-age=31536000; includeSubDomains
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Vary
        value: Origin 