services:
  - type: web
    name: quits-api
    env: node
    buildCommand: npm install
    startCommand: cd /opt/render/project/src && node index.js
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false 