services:
  - type: web
    name: quits-api
    env: node
    buildCommand: npm install
    startCommand: node src/index.js
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: PORT
        value: 10000
      - key: NODE_VERSION
        value: 22.x
    buildFilter:
      paths:
      - src/**
      - package.json
      - package-lock.json 